#.travis.yml

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 7

branches:
  only:
    - master

before_script:
  - set -e
  - npm install
  - npm install -g angular-cli-ghpages
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - ng build --prod --base-href /

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      angular-cli-ghpages --repo=https://GH_TOKEN@github.com/hassenhichri/angular5-example-app --name="New release" --email=$EMAIL --no-silent;
    fi
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    on_failure: change
    on_success: change